apiVersion: v1
kind: Service
metadata:
  name: posts-nodeport-serv
spec:
  type : NodePort
  selector:
    app: posts
  ports:
  - protocol: TCP
    port: 4000 #port our node port service running so we redirect to pod
    targetPort: 4000 #port where our pod/container running 
